baseURL = "/hugo-site"
languageCode = "en-us"
title = "Charaka"
theme = "charaka"
copyright = "&copy; <a href=\"https://gohugo.io//\">Hugo Go</a> 2019"
disqusShortname = ""
googleAnalytics = ""

[params.highlight]
  style = "zenburn"

[[params.social]]
  url = "about"
  fa_icon = "fas fa-info"

[[params.social]]
  url = "https://github.com/github"
  fa_icon = "fab fa-github"

[[params.social]]
  url = "https://twitter.com/twitter"
  fa_icon = "fab fa-twitter"

[[params.social]]
  url = "index.xml"
  fa_icon = "fab fa-rss"
