baseURL = ""
languageCode = "en-us"
title = "a minimal hugo website"
theme = "xmin"
googleAnalytics = ""
disqusShortname = ""
footnotereturnlinkcontents = "↩"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1
[[menu.main]]
    name = "About"
    url = "about/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 3
[[menu.main]]
    name = "Subscribe"
    url = "index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Yihui Xie](https://yihui.name) 2017 -- 2019 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"
